config/routes.rb
Rails.application.routes.draw do
  root 'registers#index'
 
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :registers

  get 'new', to: 'registers#new', as: 'new'
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'cities/:state', to: 'application#cities'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/register.rb
class Register < ApplicationRecord
  validates :name, :last_name, :number, :purpose, presence: :true
  validates :temp, numericality: true

  def time
    time = created_at + 7200

    time.strftime("%A, %d %B %Y,  %H:%M:%S")
  end

  def full_name
    "#{name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: {case_sensitive: false}
  validates :role, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login
  before_action :initialize_country
  before_action :initialize_namibian_regions_and_cities
  helper_method :current_user
  helper_method :current_uri

  def current_user
   if session[:user_id]
     @current_user ||= User.find(session[:user_id])
   else
     @current_user = nil
   end
  end

  def current_uri
    @current_uri = request.env['PATH_INFO']
  end

  def logged_in?
    !current_user.nil?
  end

  def cities
    render json: CS.cities(params[:state], :na).to_json
  end

  private
    def initialize_country
      @country_array = Array.new
      CS.countries.each { |k,v| @country_array.push(v) }
    end

    def initialize_namibian_regions_and_cities
      @region_array = Array.new
      @namibian_cities = Array.new

      CS.states(:na).each_key { |k| @region_array.push(k)}

      @region_array.each do |region|
        CS.cities(region, :na).each do |city|
          @namibian_cities.push(city)
          @namibian_cities.sort!
        end
      end

      @namibian_cities.push("Non-Specified")
    end

    def require_login
      unless logged_in?
        flash[:alert] = "Please login first!"
        redirect_to login_path # halts request cycle
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :require_login, only: [:index]
  def index
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_register, only: [:show, :edit, :update, :destroy]
  before_action :set_purpose_list

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)
    @action_notice = "#{@register.full_name} has been successfully saved. Welcome to RFA!"

    respond_to do |format|
      if @register.save
        format.html { redirect_to new_path, notice: @action_notice }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    def set_purpose_list
      @purpose_list = ['Attending a conference','Attending a seminar','Attending a training programme','Meeting/Workshop','Official visit','Using Cafeteria','Library','Other']
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:name, :number, :purpose, :loc_org, :temp, :last_name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create, :destroy]

  def new
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Logged in!"
    else
      redirect_to login_path, alert: "Email or password is invalid"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_roles

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_roles
      @all_roles = ['Administrator', 'Manager', 'Business Support Officer', 'Normal']
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def notification_type(type)
    case type
    when "notice"
      "alert alert-success fade in"
    when "alert"
      "alert alert-warning fade in"
    when "error"
      "alert alert-danger fade in"
    else 
      "alert alert-info fade in"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="jumbotron">
  <div class="container">
    <div class="row text-center">
      <h1>NIPAM Resource Pool</h1>
   </div>
  </div>
</section>

<section class="container">

  <%= render '/layouts/alerts' %>

  <div class="form-row">
    <!-- Specialisations -->
    <div class="form-group col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Specialisations</h3></div>
            <div class="panel-body">
              <div class="list-group">
                <%= link_to 'ADD', new_all_specialisation_path, class: 'list-group-item list-group-item-info' %>
                <%= link_to 'VIEW ALL', all_specialisations_path, class: 'list-group-item list-group-item-info' %>
              </div>
            </div>
        </div>
      </div>
    </div>
  
    <!-- Qualifications -->
    <div class="form-group col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Qualifications</h3></div>
          <div class="panel-body">
            <div class="list-group">
              <%= link_to 'ADD', new_all_qualification_path, class: 'list-group-item list-group-item-info' %>
              <%= link_to 'VIEW ALL', all_qualifications_path, class: 'list-group-item list-group-item-info' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-row">
    <!-- Skills and Competencies -->
    <div class="form-group col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Skills and Competencies</h3></div>
            <div class="panel-body">
              <div class="list-group">
                <%= link_to 'ADD', new_all_skill_path, class: 'list-group-item list-group-item-info' %>
                <%= link_to 'VIEW ALL', all_skills_path, class: 'list-group-item list-group-item-info' %>
              </div>
            </div>
        </div>
      </div>
    </div>
  
    <!-- Professional Memberships -->
    <div class="form-group col-md-6">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Professional Memberships</h3></div>
            <div class="panel-body">
              <div class="list-group">
                <%= link_to 'ADD', new_all_professional_membership_path, class: 'list-group-item list-group-item-info' %>
                <%= link_to 'VIEW ALL', all_professional_memberships_path, class: 'list-group-item list-group-item-info' %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

  <div class="form-row">
    <!-- Experts -->
    <div class="form-group col-md-12">
      <div class="panel-group">
        <div class="panel panel-default">
          <div class="panel-heading"><h3>Experts</h3></div>
            <div class="panel-body">
              <div class="list-group">
                <%= link_to 'ADD', new_person_path, class: 'list-group-item list-group-item-info' %>
                <%= link_to 'VIEW ALL', people_path, class: 'list-group-item list-group-item-info' %>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>

</section>

app/views/layouts/_alerts.html.erb
<% flash.each do |type,msg| %>
  <div class="<%= notification_type(type) %>">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <p id="<%= type %>"><%= msg %></p>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="footer navbar-fixed-bottom">
  <div class="container-fluid">
    <!-- Copyright -->
    <div class="footer-copyright py-3">© <%= Date.today.year %> Copyright:
      <a href="https://www.rfanam.com.na/"> Road Fund Administration</a>
    </div>
    <!-- Copyright -->
  </div>
</footer>
<!-- Footer -->

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default navbar-fixed-top">
    
    <div class="container-fluid">
  
      <div class="navbar-header">
        <button class="navbar-toggle" data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
      </div>
      
      <div class="navbar-collapse collapse">
  
        <ul class="nav navbar-nav">
          <li class="active"><a href="/new">New Record</a></li>
       </ul>
        
        <ul id="login-a" class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li class="dropdown">
              <a href="/#" class="dropdown-toggle" data-toggle='dropdown'>
              <%= current_user.email %> <span class='caret'>
              </a>
                <ul class="dropdown-menu">
                  <li>
                    <a href=" <%= user_path(current_user.id) %> " ><span class="glyphicon glyphicon-user"></span>
                      Profile
                    </a>
                  </li>
                  <li>
                    <a href="/logout"><span class="glyphicon glyphicon-log-out"></span>
                    Logout
                    </a>
                  </li>
                </ul>
            </li>
            </li>
          <% else %>            
            <li>
              <a href="/login"><span class="glyphicon glyphicon-log-in"></span>
              Login
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NIPAM | Resource Pool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render '/layouts/header' unless current_uri == '/new' || current_uri == '/registers' %>
    
    <div class="main">
      <%= yield %>
    </div>
    
    <%= render '/layouts/footer' unless current_uri == '/new' || current_uri == '/registers' %>
  </body>
  
</html>

app/views/registers/_form.html.erb
<%= form_with(model: register, local: true) do |form| %>
  <% if register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h4>Required fields are followed by <abbr title="Required">*</abbr></h4>
  
  <div class="form-row">
    <div class="form-group col-sm-6">
      <h4><%= form.label :first_name %> <abbr title="Required" aria-label="required">*</abbr></h4>
      <%= form.text_field :name, class: "form-control" %>
    </div>
    
    <div class="form-group col-sm-6">
      <h4><%= form.label :last_name %> <abbr title="Required" aria-label="required">*</abbr></h4>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-sm-6">
      <h4><%= form.label 'Contact Number' %> <abbr title="Required" aria-label="required">*</abbr></h4>
      <%= form.number_field :number, class: "form-control" %>
    </div>

  <div class="form-group col-sm-6">
    <div class="form-group col-sm-6">
      <h4><%= form.label :purpose %> <abbr title="Required" aria-label="required">*</abbr></h4>
      <%= form.select :purpose, @purpose_list.collect { |purpose| [purpose,purpose]}, prompt: 'Select Purpose...' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group col-sm-2 col-sm-offset-5">
      <h4><%= form.label :temperature %></h4>
      <%= form.text_field :temp, class: "form-control" %>
    </div>
  </div>

  <div class="form-row">
    <div class="actions form-group col-sm-4 col-sm-offset-4">
      <%= form.submit 'Submit', class: 'btn btn-success', id: "register-submit" %> <hr />
    </div>
  </div>

<% end %>

app/views/registers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="form-group col-md-8 col-md-offset-2">
      <legend><h1>Edit Register for: <%= @register.full_name %> </h1></legend>

      <%= render 'form', register: @register %>

      
      <div class="form-row">
        <div class="form-group col-sm-12">
          <%= link_to 'Back', @register %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/registers/index.html.erb
<%= render '/layouts/header' %>

<div class="container">
  <%= render '/layouts/alerts' %>

  <h1>Registers</h1>
  <br />

  <div class="row">
    <div clas="col-md-12">
      <table id="static-table" class="display">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Number</th>
            <th>Date and Time</th>
            <th>Purpose</th>
            <th>Temperature</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @registers.each do |register| %>
            <tr>
              <td><%= register.name %></td>
              <td><%= register.last_name %></td>
              <td><%= register.number %></td>
              <td><%= register.time %></td>
              <td><%= register.purpose %></td>
              <td><%= register.temp %></td>
              <td><%= link_to 'View', register, class: "btn btn-success" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <br>

</div>

<%= render '/layouts/footer' %>

app/views/registers/new.html.erb
<body style="background-image: url('rfa-background1.jpg'); background-size: 100% 100%;">
<div id="new-register">
  <div class="container">
    <div class="row">
      <div class="form-group col-md-8 col-md-offset-2">
        <%= render '/layouts/alerts' %>
        <%= image_tag("rfa-logo1.jpeg", alt: 'NIPAM', id: "rfa-logo", style: "border-radius: 45%;") %>
        <legend><h1 id="rfa-welcome-heading">RFA VISITOR'S REGISTER</h1></legend>

        <%= render 'form', register: @register %>

      </div>
    </div>
  </div>
</div>
</body>

app/views/registers/show.html.erb
<div class="container">
  <div class="jumbotron">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Name:</strong>
      <%= @register.full_name %>
    </p>

    <p>
      <strong>Number:</strong>
      <%= @register.number %>
    </p>

    <p>
      <strong>Date and Time:</strong>
      <%= @register.time %>
    </p>

    <p>
      <strong>Purpose:</strong>
      <%= @register.purpose %>
    </p>

    <p>
      <strong>Temperature:</strong>
      <%= @register.temp %>
    </p>

    <%= link_to 'Edit', edit_register_path(@register) %> |
    <%= link_to 'Back', registers_path %> |
    <%= link_to 'Delete', @register, method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>Required fields are followed by <abbr title="Required">*</abbr></p>
  
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :email %> <abbr title="Required" aria-label="required">*</abbr> <br />
      <%= form.text_field :email, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :role %> <abbr title="Required" aria-label="required">*</abbr> <br />
      <%= form.select :role, @all_roles.collect { |role| [role,role]}, prompt: 'Select Role...',class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :password %> <abbr title="Required" aria-label="required">*</abbr> <br />
      <%= form.password_field :password, class: 'form-control' %>
    </div>
  </div>
  
  <div class="form-row">
    <div class="form-group col-md-12">
      <%= form.label :password_confirmation %> <abbr title="Required" aria-label="required">*</abbr> <br />
      <%= form.password_field :password_confirmation, class: 'form-control' %>
    </div>  
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

<hr />

app/views/users/edit.html.erb
<div class="container">

    <div class="row">
      <div class="form-group col-md-4 col-md-offset-4">
        <legend><h1>Editing <%= @user.email %> </h1></legend>
        <%= render 'form', user: @user %>
        <%= link_to 'Back', users_path, class: 'btn btn-primary' %>
      </div>
    </div>

</div>

app/views/users/index.html.erb
<div class="container">
<%= render '/layouts/alerts' %>
<h1>Users</h1>

  <div class="row">
    <div class="col-md-12">
      <table id="users-table" class="display">
        <thead>
          <tr>
            <th>Email</th>
            <th>Role</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.email %></td>
              <td><%= user.role %></td>
              <td><%= link_to 'Show', user %></td>
              <td><%= link_to 'Edit', edit_user_path(user) %></td>
              <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <br>
  
  <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>

</div>

app/views/users/new.html.erb
<div class="container">

    <div class="row">
      <div class="form-group col-md-4 col-md-offset-4">
        <legend><h1>Sign Up</h1></legend>
        <%= render 'form', user: @user %>
        <%= link_to 'Back', users_url, class: 'btn btn-primary' %>
      </div>
    </div>
    
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render '/layouts/alerts' %>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= @user.role %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user), class: 'btn btn-primary' %>
</div>